name: gofit
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  booking_calendar: ^1.1.9
  cloud_firestore: ^4.7.1
  dots_indicator: ^2.1.0
  dropdown_button2: ^2.1.3
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_naver_map: ^1.0.1
  flutter_stripe: ^9.2.0
  fluttertoast: ^8.2.1
  get: ^4.6.5
  image_picker: ^0.8.7+5
  intl: ^0.17.0
  kakao_map_plugin: ^0.1.4
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf

  assets:
    - assets/images/
